# Generated by Django 5.1.1 on 2024-09-25 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_image', models.ImageField(upload_to='pics')),
                ('food_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=4)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('food_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.snacks')),
                ('table_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.tables')),
            ],
        ),
    ]
