# Generated by Django 5.1.1 on 2024-09-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_snacks_tables_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='quantity',
            field=models.CharField(max_length=2),
        ),
    ]
