# Generated by Django 5.1.1 on 2024-09-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_tables_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
