# Generated by Django 5.1.1 on 2024-09-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_order_food_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='members',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tables',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
