# Generated by Django 5.1.1 on 2024-09-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_order_members_alter_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table_name',
            field=models.CharField(max_length=4),
        ),
    ]
