# Generated by Django 5.1.1 on 2024-09-25 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_order_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.tables'),
        ),
    ]
