# Generated by Django 5.1.1 on 2024-09-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_order_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table_name',
            field=models.CharField(max_length=4),
        ),
    ]
