# Generated by Django 5.1.1 on 2024-09-26 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='total_price',
            new_name='total_amount',
        ),
    ]
