# Generated by Django 5.1.1 on 2024-09-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_rename_total_price_payment_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='table_book',
            field=models.CharField(default='none', max_length=4),
            preserve_default=False,
        ),
    ]
