# Generated by Django 5.1.1 on 2024-09-27 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_payment_table_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='table_book',
        ),
    ]
